# Minimal test configuration for train_grpo_qwen_image.py
# This runs a very short training to verify the script works

# Model configuration
model_name_or_path: Qwen/Qwen2.5-VL-7B-Instruct
gen_model_path: Qwen/Qwen-Image
output_dir: /tmp/test_grpo_qwen_image

# Training configuration - MINIMAL for testing
learning_rate: 1e-5
num_train_epochs: 1
max_steps: 2  # Just 2 steps to test
per_device_train_batch_size: 1
gradient_accumulation_steps: 1

# Prompt/completion lengths
max_prompt_length: 512  # Reduced for speed
max_completion_length: 128  # Reduced for speed

# Dataset configuration - MINIMAL
levels: preschool  # Single level only
disciplines: Math  # Single discipline only

# GRPO configuration
num_generations: 2  # Minimal generations per prompt
generation_batch_size: 2
loss_type: dr_grpo

# Evaluation configuration
alignment_weight: 0.7
quality_weight: 0.3
n_evals: 1  # Single evaluation instead of 3

# Logging
logging_steps: 1
save_strategy: "no"  # Don't save checkpoints for test
report_to: none  # Don't report to wandb

# Model optimization
dtype: bfloat16
use_peft: true
lora_target_modules:
  - q_proj
  - v_proj
lora_r: 8  # Minimal LoRA rank
lora_alpha: 16
gradient_checkpointing: false

# vLLM settings
use_vllm: false  # Disable for simpler testing


